### ISSUE TITLE
unknown feature `raw`

### ISSUE THREAD

**Issue by mward** [rrevenantt/antlr4rust#34] opened 2021-09-13 12:48 UTC
Unable to compile `antlr4rs` because of the following:

```
error[E0635]: unknown feature `raw`
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/antlr-rust-0.2.0/src/lib.rs:4:12
  |
4 | #![feature(raw)]
  |  
```

If I remove that line compilation continues without anymore errors. 

Thanks!

**Comment by newca12** [comment] 2021-10-17 06:46
This is a duplicate of #25

**Closed** 2022-07-22 13:59 UTC
